/**
 * Copyright Sung-tae Ryu. All rights reserved.
 * Code licensed under the GPL v2 License:
 * http://www.goorm.org/License
 * version: 3.0.0
 * This is the module example for YUI_DOCS
 * @module collaboration
 **//**
 * This is an goorm code generator.  
 * goorm starts with this code generator.
 * @class join_project
 * @extends collaboration
 **/org.goorm.core.collaboration.join=function(){this.dialog=null,this.buttons=null,this.tabview=null,this.treeview=null,this.chat=null},org.goorm.core.collaboration.join.prototype={init:function(){var e=this,t=function(){var t=this;$("#join_project_contents #project_list .selector_project").hasClass("selected_button")?$("#join_project_contents #project_list .selected_button").each(function(){e.chat.set_chat_off(),core.dialog.open_project.open($(this).attr("project_path"),$(this).attr("project_name"),$(this).attr("projectType")),core.flag.collaboration_on||$("a[action=collaboration_edit_on_off]").click(),core.collaboration_draw_on||$("a[action=collaboration_draw_on_off]").click(),t.hide()}):alert.show(core.module.localization.msg.alertCollaborationSelect)},n=function(){this.hide(),e.chat&&e.chat.set_chat_off()};this.buttons=[{text:"Join",handler:t,isDefault:!0},{text:"Cancel",handler:n}],this.dialog=new org.goorm.core.collaboration.join.dialog,this.dialog.init({title:"Join Online Project",path:"configs/dialogs/org.goorm.core.collaboration/collaboration.join.html",width:700,height:500,modal:!0,buttons:this.buttons,success:function(){e.tabview=new YAHOO.widget.TabView("join_project_contents"),e.treeview=new YAHOO.widget.TreeView("join_project_treeview"),e.treeview.render(),$("#join_project_contents").children("div").css("padding","0px")}}),this.dialog=this.dialog.dialog},show:function(){var e=this;this.dialog.panel.show(),e.chat=new org.goorm.core.collaboration.chat,e.chat.init("chat_join_online_project"),$("#join_project_contents #project_list").html(""),e.add_project_list(),this.chat.is_chat_on||this.chat.set_chat_on()},add_project_list:function(){var postdata={kind:"project",project_name:"",folder_only:"false"};$.post("file/get_nodes",postdata,function(data){var sort_function=function(e,t){return e.cls>t.cls?-1:e.cls<t.cls?1:0},sort_project_treeview=function(e){e.sort(sort_function);for(i=0;i<e.length;i++)e[i].children&&sort_project_treeview(e[i].children)},sorting_data=eval(data),counter=0;for(var name in sorting_data)if(sorting_data[name].cls=="folder"){var icon_str="",url={path:"../../project/"+sorting_data[name].filename+"/project.xml"};counter++,$.get("file/get_contents",url,function(e){if(e&&$(e).find("COLLABORATION").text()=="true"){var t=$(e).find("AUTHOR").text()+"_"+$(e).find("NAME").text();icon_str="<div id='selector_"+t+"' project_path='"+t+"' project_name='"+$(e).find("NAME").text()+"' projectType='"+$(e).find("TYPE").text()+"' class='selector_project'>",icon_str+="<div style='padding-left:65px; padding-top:20px;'>",icon_str+=t,icon_str+="</div>",icon_str+="</div>",$("#join_project_contents #project_list").append(icon_str)}counter--,counter==0&&$("#join_project_contents #project_list .selector_project").click(function(){$("#join_project_contents #project_list .selector_project").removeClass("selected_button"),$(this).addClass("selected_button")})})}})}};